---
services: docker

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos6
    init: /sbin/init
    run_opts: ""

before_install:
  # Pull container.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/ocsinventory-agent:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  # Remove default Ansible version and install the 2.2
  - if [[ "${distro}" == "centos6" ]]; then docker exec --tty "$(cat ${container_id})" env TERM=xterm yum -y install gcc gmp-devel gcc gmp-devel; fi
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum -y remove ansible'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum -y install python-pip'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm pip install ansible==2.2.0'

  # Install the ansible galaxy roles included in the test playbook
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install geerlingguy.repo-epel'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install geerlingguy.repo-remi'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/ocsinventory-agent/tests/test.yml --syntax-check'

  # Test role.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/ocsinventory-agent/tests/test.yml'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ocsinventory-agent/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

   # Run tests in Container
  #- tests/docker_setup.sh ${OS_VERSION}

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
